# Generated by Django 4.2.4 on 2023-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=25)),
                ('mylink', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'My Website',
            },
        ),
    ]
